### ISSUE TITLE
Facebook login not working anymore

### ISSUE THREAD

**Issue by skoften** [dukt/social#35]
The Facebook login stopped working; the account is created, but not logged in.

Logs:

```
2019-05-20 14:06:35 [-][-][-][error][dukt\social\controllers\LoginAccountsController::actionLogin] Couldn‚Äôt login. #0 [internal function]: dukt\social\controllers\LoginAccountsController->actionLogin()
#1 /var/www/new/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/new/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/new/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('login', Array)
#4 /var/www/new/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('login', Array)
#5 /var/www/new/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('social/login-ac...', Array)
#6 /var/www/new/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('social/login-ac...', Array)
#7 /var/www/new/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /var/www/new/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/new/web/index.php(21): yii\base\Application->run()
#10 {main}
2019-05-20 14:06:35 [-][-][-][info][application] $_GET = []
```

```
    'error' => 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry \'facebook-1121758954569911\' for key \'social_login_accounts_providerHandle_socialUid_unq_idx\'
The SQL being executed was: INSERT INTO `social_login_accounts` (`id`, `userId`, `providerHandle`, `socialUid`, `dateCreated`, `dateUpdated`, `uid`) VALUES (164683, 164681, \'facebook\', \'1121758954569911\', \'2019-05-20 11:50:19\', \'2019-05-20 11:50:19\', \'82edffe6-4c83-4620-90c2-8cf0e05ab67b\')'
```

Using Craft CMS 3.1.27

**Comment by benjamindavid** [comment]
Hey @skoften, sorry about that. There’s an issue with the way Social handles soft deletes, a fix is on the way.

Related: https://github.com/dukt/social/issues/32

**Comment by benjamindavid** [comment]
Fixed by https://github.com/dukt/social/commit/7789da785ee18da3cc5ef631868caf201ab0c764

**Comment by skoften** [comment]
Thanks, but unfortunately it's still not working. 

Log is showing:  'error' => 'Social account exists but Craft user doesn‚Äôt.'

**Comment by benjamindavid** [comment]
@skoften Seems like a different error. Can you please check your `social_login_accounts` table and check if the corresponding login account has a `userId` value defined. If that's the case, does the related user still exist or has it been deleted? Thanks!

**Comment by skoften** [comment]
I just deleted the user from Craft users, to test a "clean" registration. But the user isn't created anymore.

About the social_login_accounts table; looks like there hasn't been an row added for weeks;

<img width="1285" alt="Screenshot 2019-05-20 at 19 56 48" src="https://user-images.githubusercontent.com/1286410/58041852-6f2bbb00-7b39-11e9-88b7-6fab3eef928c.png">

**Comment by benjamindavid** [comment]
Have you tried deleting trashed data?
```./craft gc --delete-all-trashed=1```
https://docs.craftcms.com/v3/gc.html#forcing-garbage-collection

**Comment by skoften** [comment]
Great, that solved it. Thanks!
